#!/bin/bash
# Author: David Latham <kiwilathams@gmail.com>
# License: GPL v.2
#
### BEGIN INIT INFO
# Provides:		ip6tables
# Default-Start:	3 4 5
# Default-Stop:		0 1 2 6
# Short-Description:	Traditional ip6tables Implimentation (IPv6)
# Long-Description:	Replacement for SuSEFirewall2 daemon that provides
#	for the traditional configuration of ip6tables (IPv6) via
#	/etc/sysconfig/ip6tables
### END INIT INFO


IPT=/usr/sbin/ip6tables
IPTsave=/usr/sbin/ip6tables-save
IPTrestore=/usr/sbin/ip6tables-restore

IPTConfigSave=/etc/sysconfig/ip6tables.save
IPTConfigOpen=/etc/sysconfig/ip6tables.open

action=$1; shift

usage() {
cat <<EOT
usage: $0 <start|stop|status>
	start: Load the ip6tables configuration in /etc/sysconfig/ip6tables.save
	stop:  Load the ip6tables configuration in /etc/sysconfig/ip6tables.open
		** NOTE ** Stopping ip6tables actually creates a completely open firewall
	status: Display the current ip6tables rules.
	restart: open the firewall and close it again with ip6tables.open and ip6tables.save
EOT
}

if [ -z $action ]; then
	usage
	exit 1
fi


# Shell functions sourced from /etc/rc.status:
#      rc_check         check and set local and overall rc status
#      rc_status        check and set local and overall rc status
#      rc_status -v     ditto but be verbose in local rc status
#      rc_status -v -r  ditto and clear the local rc status
#      rc_failed        set local and overall rc status to failed
#      rc_failed <num>  set local and overall rc status to <num><num>
#      rc_reset         clear local rc status (overall remains)
#      rc_exit          exit appropriate to overall rc status
. /etc/rc.status

case $action in
	"start")
		echo -n "Stopping SuSEfirewall2..."
		rc_status -v
		systemctl stop SuSEfirewall2
		echo -n "Starting ip6tables..."
		$IPTrestore < $IPTConfigSave
		rc_status -v
		;;
	"stop")
		echo -n "Stopping ip6tables ..."
		$IPTrestore < $IPTConfigOpen
		rc_status -v
		;;
	"restart")
		$0 stop
		$0 start
		;;
	"status")
		echo -n "Checking for ip6tables..."
		$IPTsave
		rc_status -v
		;;
	*)
		usage
		exit 1
esac
