#!/bin/bash
# Author: David Latham <kiwilathams@gmail.com>
# License: GPL v.2
#
### BEGIN INIT INFO
# Provides:		iptables
# Default-Start:	3 4 5
# Default-Stop:		0 1 2 6
# Short-Description:	Traditional Itables Implimentation (IPv4)
# Long-Description:	Replacement for SuSEFirewall2 daemon that provides
#	for the traditional configuration of iptables (IPv4) via
#	/etc/sysconfig/iptables
### END INIT INFO


IPT=/usr/sbin/iptables
IPTsave=/usr/sbin/iptables-save
IPTrestore=/usr/sbin/iptables-restore

IP6T=/usr/sbin/ip6tables
IP6Tsave=/usr/sbin/ip6tables-save
IP6Trestore=/usr/sbin/ip6tables-restore

IPTConfigSave=/etc/sysconfig/iptables.save
IPTConfigOpen=/etc/sysconfig/iptables.open

action=$1; shift

usage() {
cat <<EOT
usage: $0 <start|stop|status>
	start: Load the iptables configuration in /etc/sysconfig/iptables.save
	stop:  Load the iptables configuration in /etc/sysconfig/iptables.open
		** NOTE ** Stopping iptables actually creates a completely open firewall
	status: Display the current iptables rules.
	restart: open the firewall and close it again with iptables.open and iptables.save
EOT
}

if [ -z $action ]; then
	usage
	exit 1
fi


# Shell functions sourced from /etc/rc.status:
#      rc_check         check and set local and overall rc status
#      rc_status        check and set local and overall rc status
#      rc_status -v     ditto but be verbose in local rc status
#      rc_status -v -r  ditto and clear the local rc status
#      rc_failed        set local and overall rc status to failed
#      rc_failed <num>  set local and overall rc status to <num><num>
#      rc_reset         clear local rc status (overall remains)
#      rc_exit          exit appropriate to overall rc status
. /etc/rc.status

case $action in
	"start")
		echo -n "Stopping SuSEfirewall2..."
		rc_status -v
		systemctl stop SuSEfirewall2
		echo -n "Starting iptables..."
		$IPTrestore < $IPTConfigSave
		rc_status -v
		echo -n "enabling ipv4.ip_forward"
		sysctl net.ipv4.ip_forward=1
		rc_status -v
		;;
	"stop")
		echo -n "Stopping iptables ..."
		$IPTrestore < $IPTConfigOpen
		rc_status -v
		;;
	"restart")
		$0 stop
		$0 start
		;;
	"status")
		echo -n "Checking for iptables..."
		$IPTsave
		rc_status -v
		;;
	*)
		usage
		exit 1
esac
